"""Generate the predictive-vs-causal map figure.

Single scatter panel: |SHAP| (predictive importance) vs |probe tau_hat|
(causal estimate), one point per motif key feature. The 2x2 grid of
descriptive cells (actionable / underused / irrelevant / predictive-
only) is created by midline thresholds on the non-negative magnitude
axes — these are not signed quadrants.

SHAP comes from path-dependent TreeSHAP via LightGBM (matches the
paper's existing Hillstrom SHAP-vs-probe methodology in
`causal_probe/run_baseline.py:shap_tau`). The other three predictive-
attribution baselines from \\cref{tab:predictive-baselines} (marginal
correlation, linear regression, permutation importance) are computed
in the same JSON for future use, but only SHAP is plotted here.

Inputs:
  - causal_probe/results/eval_main_p5_50k.json (probe tau_hat per
    motif feature)
  - causal_probe/results/motif_pred_baselines_p5.json (SHAP per motif
    feature, generated by causal_probe/compute_motif_pred_baselines.py)

Output: paper/figures/predictive_vs_causal.pdf
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


MOTIFS_JSON = "causal_probe/results/eval_main_p5_50k.json"
PRED_BASELINES_JSON = "causal_probe/results/motif_pred_baselines_p5.json"
OUT_PDF = "paper/figures/predictive_vs_causal.pdf"


_KEY_FEATURES = {
    # motif name in eval JSON -> [(feature index, point label)]
    "A_direct_cause":         [(0, r"$X_1$ direct cause")],
    "B_proxy":                [(1, r"$X_2$ proxy")],
    "C_observed_confounder":  [(0, r"$X_1$ confounded")],
    "D_mediator":             [(0, r"$X_1$ upstream"),
                               (1, r"$X_2$ mediator")],
    "E_target_descendant":    [(0, r"$X_1$ leak")],
    "F_collider_leakage":     [(1, r"$C$ collider")],
}
_MOTIF_COLOR = {
    "A_direct_cause": "#2ca02c",
    "B_proxy": "#ff7f0e",
    "C_observed_confounder": "#9467bd",
    "D_mediator": "#1f77b4",
    "E_target_descendant": "#d62728",
    "F_collider_leakage": "#8c564b",
}
_NOISE_COLOR = "#bbbbbb"


def _decorate_2x2(ax, xlim, ylim):
    """Midline thresholds split [0, xlim] x [0, ylim] into four
    descriptive cells. The two axes are different magnitudes (|SHAP|
    in tau-scale units; |tau_hat| in standardized-contrast units), so
    each axis gets its own midline at half its observed maximum range.
    These are not signed quadrants."""
    xm, ym = xlim / 2.0, ylim / 2.0
    ax.axvline(xm, color="gray", linewidth=0.7, linestyle="--", alpha=0.7)
    ax.axhline(ym, color="gray", linewidth=0.7, linestyle="--", alpha=0.7)
    txt_kw = dict(fontsize=10, color="gray", alpha=0.95,
                  bbox=dict(facecolor="white", alpha=0.9,
                            edgecolor="none", pad=2.0))
    # Cell labels at outer corners. Stored on the axes so the caller can
    # pass them as static obstacles to adjust_text (so data labels won't
    # overlap them).
    ax._cell_labels = [
        ax.text(0.02, 0.97, "causal only",
                ha="left",  va="top", transform=ax.transAxes, **txt_kw),
        ax.text(0.98, 0.97, "causal + predictive",
                ha="right", va="top", transform=ax.transAxes, **txt_kw),
        ax.text(0.02, 0.47, "neither",
                ha="left",  va="top", transform=ax.transAxes, **txt_kw),
        ax.text(0.98, 0.47, "predictive only",
                ha="right", va="top", transform=ax.transAxes, **txt_kw),
    ]
    ax.set_xlim(0, xlim)
    ax.set_ylim(0, ylim)


def _motifs_panel(ax):
    eval_d = json.load(open(MOTIFS_JSON))
    base_d = json.load(open(PRED_BASELINES_JSON))
    points = []  # (motif_name, feat_idx, label, pred, causal)
    for name, key_feats in _KEY_FEATURES.items():
        eval_rows = {r["feature"]: r for r in
                     eval_d.get("motifs", {}).get(name, {}).get("rows", [])}
        base_rows = {r["feature"]: r for r in
                     base_d.get("motifs", {}).get(name, {}).get("rows", [])}
        for feat_idx, label in key_feats:
            er = eval_rows.get(feat_idx)
            br = base_rows.get(feat_idx)
            if er is None or br is None:
                continue
            points.append((
                name, feat_idx, label,
                abs(float(br.get("shap_mean", 0.0))),
                abs(float(er.get("tau_hat_mean", 0.0))),
            ))
    if not points:
        ax.text(0.5, 0.5, "no motif data", ha="center", va="center",
                transform=ax.transAxes, fontsize=11, color="gray")
        return

    pred = np.asarray([p[3] for p in points])
    causal = np.asarray([p[4] for p in points])
    # Independent axis ranges: |SHAP| (TreeSHAP/std(y)) and |tau_hat|
    # (standardized contrast) live on different scales — sharing a lim
    # would push the SHAP midline above any data, leaving the
    # "actionable" and "predictive-only" cells permanently empty.
    xlim = float(pred.max()) * 1.15
    ylim = float(causal.max()) * 1.15

    # Plot points and seed text artists at each point's position.
    seen = set()
    text_artists = []
    point_xs, point_ys = [], []
    for name, _idx, label, x, y in points:
        color = _MOTIF_COLOR[name]
        legend_lbl = None
        if name not in seen:
            legend_lbl = name.replace("_", " ")
            seen.add(name)
        ax.scatter(x, y, c=color, s=140,
                   edgecolors="black", linewidth=0.6,
                   label=legend_lbl, zorder=3)
        text_artists.append(ax.text(x, y, label, fontsize=9, zorder=4))
        point_xs.append(x); point_ys.append(y)

    # x-axis quantity is mean |TreeSHAP| (convention: feature importance
    # in the SHAP literature is the magnitude). Caption notes that.
    # y-axis quantity is the probe's tau_hat — labelled as the conceptual
    # "feature intervention effect" since the figure's contract is about
    # what the quantity *is*, not the estimator distinction tau vs tau_hat
    # (which the paper's main text owns).
    ax.set_xlabel(r"SHAP  (feature importance, $|\mathrm{TreeSHAP}|$)")
    ax.set_ylabel(r"FADO  (feature intervention effect, $\hat\tau$)")
    ax.set_title("Predictive vs causal explainability on motifs A–F")
    _decorate_2x2(ax, xlim, ylim)

    # Auto-place data labels to avoid overlap with each other, the
    # markers, AND the cell labels. Cell labels live on `ax._cell_labels`
    # (set by _decorate_2x2) and are passed in as static obstacles.
    from adjustText import adjust_text
    adjust_text(
        text_artists,
        x=point_xs, y=point_ys,
        ax=ax,
        objects=getattr(ax, "_cell_labels", []),
        arrowprops=dict(arrowstyle="-", color="gray", alpha=0.6, lw=0.6),
        expand=(1.6, 2.0),
        force_text=(0.8, 1.4),
        force_static=(1.2, 1.6),
        iter_lim=200,
    )


_DAG_SPECS = [
    # (motif key for color, title, nodes={label: (x, y)},
    #  edges=[(src_label, dst_label)], highlight=[label_to_color],
    #  hidden=[label_to_render_dashed])
    ("A_direct_cause", r"(A) direct cause",
     {r"$X_1$": (-0.6, 0), r"$Y$": (0.6, 0)},
     [(r"$X_1$", r"$Y$")],
     [r"$X_1$"], []),
    ("B_proxy", r"(B) proxy",
     {r"$X_1$": (-0.6, 0), r"$Y$": (0.6, 0.4), r"$X_2$": (0.6, -0.4)},
     [(r"$X_1$", r"$Y$"), (r"$X_1$", r"$X_2$")],
     [r"$X_2$"], []),
    ("C_observed_confounder", r"(C) observed confounder",
     {r"$X_1$": (-0.6, -0.2), r"$Y$": (0.6, -0.2), r"$Z$": (0, 0.5)},
     [(r"$Z$", r"$X_1$"), (r"$Z$", r"$Y$")],
     [r"$X_1$"], []),
    ("D_mediator", r"(D) mediator",
     {r"$X_1$": (-0.75, 0), r"$X_2$": (0, 0), r"$Y$": (0.75, 0)},
     [(r"$X_1$", r"$X_2$"), (r"$X_2$", r"$Y$")],
     [r"$X_1$", r"$X_2$"], []),
    ("E_target_descendant", r"(E) target descendant (label leak)",
     {r"$Y$": (-0.6, 0), r"$X_1$": (0.6, 0)},
     [(r"$Y$", r"$X_1$")],
     [r"$X_1$"], []),
    ("F_collider_leakage", r"(F) collider",
     {r"$X_1$": (-0.6, 0.4), r"$Y$": (0.6, 0.4), r"$C$": (0, -0.4)},
     [(r"$X_1$", r"$C$"), (r"$Y$", r"$C$")],
     [r"$C$"], []),
]


def _draw_dag(ax, motif_key, title, nodes, edges, highlight, hidden=()):
    """Draw a single mini-DAG with the highlight node coloured by motif.
    Nodes in ``hidden`` render with a dashed border and lighter face — for
    unobserved variables (e.g. hidden confounder Z in motif C)."""
    from matplotlib.patches import Circle, FancyArrowPatch

    ax.set_xlim(-1, 1)
    ax.set_ylim(-0.8, 0.8)
    ax.set_aspect("equal")
    ax.set_xticks([]); ax.set_yticks([])
    for s in ax.spines.values():
        s.set_visible(False)
    # Motif E's title ("(E) target descendant (label leak)") is wider than
    # the (E) DAG axes, so it bleeds past the surrounding gray box on the
    # left. Shift its title slightly right so it stays inside the box.
    if motif_key == "E_target_descendant":
        ax.set_title(title, fontsize=9, x=0.62)
    else:
        ax.set_title(title, fontsize=9)

    color = _MOTIF_COLOR[motif_key]
    radius = 0.16
    for label, (x, y) in nodes.items():
        is_hidden = label in hidden
        if label == r"$Y$":
            face, edge_c, text_color, fw = "#ffffff", "black", "black", "bold"
        elif label in highlight:
            face, edge_c, text_color, fw = color, "black", "white", "bold"
        elif is_hidden:
            face, edge_c, text_color, fw = "#f0f0f0", "#888888", "#888888", "normal"
        else:
            face, edge_c, text_color, fw = "#dddddd", "black", "black", "normal"
        c = Circle((x, y), radius, facecolor=face, edgecolor=edge_c,
                   linewidth=1.0,
                   linestyle="--" if is_hidden else "-",
                   zorder=3)
        ax.add_patch(c)
        ax.text(x, y, label, ha="center", va="center",
                fontsize=9, fontweight=fw, color=text_color, zorder=4)

    for src, dst in edges:
        x1, y1 = nodes[src]
        x2, y2 = nodes[dst]
        dx, dy = x2 - x1, y2 - y1
        d = np.hypot(dx, dy)
        ux, uy = dx / d, dy / d
        x1t, y1t = x1 + ux * radius, y1 + uy * radius
        x2t, y2t = x2 - ux * radius, y2 - uy * radius
        ar = FancyArrowPatch((x1t, y1t), (x2t, y2t),
                             arrowstyle="-|>", mutation_scale=12,
                             linewidth=1.0, color="#444444", zorder=2)
        ax.add_patch(ar)


def _pack_dag_rows(dag_axes, y_bottom):
    """Compress the 3x2 DAG grid vertically so it fits inside the same
    top/bottom span as the square scatter panel.

    We keep the top row fixed and shrink the two inter-row gaps evenly.
    That lifts the middle row slightly and the bottom row a bit more,
    removing the excess whitespace that otherwise leaves motif F hanging
    below the gray background box.
    """
    top_row = dag_axes[:2]
    row_height = top_row[0].get_position().height
    top_y1 = max(ax.get_position().y1 for ax in top_row)
    row_gap = (top_y1 - y_bottom - 3.0 * row_height) / 2.0
    row_gap = max(row_gap, 0.0)
    row_y0s = [
        top_y1 - row_height,
        top_y1 - 2.0 * row_height - row_gap,
        top_y1 - 3.0 * row_height - 2.0 * row_gap,
    ]
    for row_idx in range(3):
        for ax in dag_axes[2 * row_idx: 2 * row_idx + 2]:
            pos = ax.get_position()
            ax.set_position([pos.x0, row_y0s[row_idx], pos.width, pos.height])


def main():
    import matplotlib.gridspec as gridspec

    fig = plt.figure(figsize=(13, 7))
    # Extra-thin top row acts as a header buffer so the DAG titles ("(A)
    # direct cause", ...) sit BELOW the "Motifs" / scatter-title
    # baseline. Scatter axes still span all rows for full height.
    gs = gridspec.GridSpec(
        4, 4, figure=fig,
        width_ratios=[1.0, 1.0, 0.15, 2.5],
        height_ratios=[0.18, 1.0, 1.0, 1.0],
        wspace=0.25, hspace=0.45,
    )
    dag_axes = [fig.add_subplot(gs[r + 1, c])
                for r in range(3) for c in range(2)]
    for ax_dag, spec in zip(dag_axes, _DAG_SPECS):
        _draw_dag(ax_dag, *spec)
        # Transparent axes face so the figure-level gray box shows through.
        ax_dag.set_facecolor("none")

    ax_scatter = fig.add_subplot(gs[:, 3])
    _motifs_panel(ax_scatter)
    # Keep the explainability panel genuinely square instead of letting the
    # GridSpec cell stretch it vertically with the overall figure canvas.
    ax_scatter.set_box_aspect(1)

    # Once the scatter panel becomes square, it no longer spans the full
    # GridSpec cell vertically. Re-pack the DAG rows into that shorter span
    # so the lower motifs stay inside the gray box without manual per-motif
    # nudges.
    fig.canvas.draw()
    _pack_dag_rows(dag_axes, ax_scatter.get_position().y0)

    # "Motifs" header centred over the DAG block. Same font + weight as
    # the scatter title so the two read as siblings; vertical position
    # matched to the scatter title's baseline (computed after a draw so
    # the title's renderer-resolved bbox is available).
    fig.canvas.draw()
    fig_inv = fig.transFigure.inverted()
    title_bbox = ax_scatter.title.get_window_extent()
    motifs_y = fig_inv.transform((0, title_bbox.y0))[1]
    top_left_bbox = dag_axes[0].get_position()
    top_right_bbox = dag_axes[1].get_position()
    motifs_x = (top_left_bbox.x0 + top_right_bbox.x1) / 2
    fig.text(motifs_x, motifs_y, "Motifs",
             ha="center", va="bottom",
             fontsize=plt.rcParams["axes.titlesize"],
             fontweight=plt.rcParams["axes.titleweight"])

    # Light gray box surrounding only the DAG block. Vertical extent
    # matches the scatter axes (right panel) exactly; "Motifs" header
    # sits above the box, aligned with the scatter title.
    from matplotlib.patches import Rectangle
    pad_x = 0.018
    scatter_pos = ax_scatter.get_position()
    box_left = min(ax.get_position().x0 for ax in dag_axes) - pad_x
    box_right = max(ax.get_position().x1 for ax in dag_axes) + pad_x
    box_top = scatter_pos.y1
    box_bottom = scatter_pos.y0
    rect = Rectangle(
        (box_left, box_bottom),
        box_right - box_left, box_top - box_bottom,
        transform=fig.transFigure,
        facecolor="#eeeeee", edgecolor="#bbbbbb", linewidth=0.8,
        zorder=0,
    )
    fig.add_artist(rect)

    Path(OUT_PDF).parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUT_PDF, bbox_inches="tight")
    fig.savefig(OUT_PDF.replace(".pdf", ".png"), dpi=150, bbox_inches="tight")
    print(f"wrote {OUT_PDF}")


if __name__ == "__main__":
    main()
