"""Auto-generate every numeric table in paper/main.tex from results JSONs.

Each function emits paper/tables/<name>.tex containing only the
\\begin{tabular}…\\end{tabular} block. main.tex wraps these in
\\begin{table}…\\end{table} with the caption / label / placement.

Run from repo root:  uv run python scripts/build_tables.py

Outputs are deterministic (fixed bootstrap seed = 2025, B = 5000)
so re-running with no JSON changes produces byte-identical .tex files.
"""
from __future__ import annotations

import json
import math
import os
from pathlib import Path
from typing import Iterable

import numpy as np

REPO = Path(__file__).resolve().parent.parent
RESULTS = REPO / "causal_probe" / "results"
BOOT = RESULTS / "bootstrap"
TABLES = REPO / "paper" / "tables"

BOOT_B = 5000
BOOT_SEED = 2025

HEADER = "% Auto-generated by scripts/build_tables.py — do not hand-edit\n"


def _load(path: Path) -> dict:
    with open(path) as f:
        return json.load(f)


def _write(name: str, body: str, comment: str = "") -> None:
    out = TABLES / f"{name}.tex"
    with open(out, "w") as f:
        f.write(HEADER)
        if comment:
            f.write(f"% {comment}\n")
        f.write(body)
        if not body.endswith("\n"):
            f.write("\n")
    print(f"  wrote {out.relative_to(REPO)}")


def _fz_ci(r: float, n: int, conf: float = 0.95) -> tuple[float, float]:
    """Fisher-z CI for a Pearson/Spearman correlation."""
    if n < 4 or not np.isfinite(r) or abs(r) >= 1:
        return (float("nan"), float("nan"))
    z = math.atanh(r)
    se = 1 / math.sqrt(n - 3)
    z_crit = 1.959964
    return math.tanh(z - z_crit * se), math.tanh(z + z_crit * se)


def _wilson(p: float, n: int, conf: float = 0.95) -> tuple[float, float]:
    z = 1.959964
    if n <= 0:
        return float("nan"), float("nan")
    den = 1 + z * z / n
    cen = (p + z * z / (2 * n)) / den
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
    return cen - half, cen + half


def _bootstrap_pearson(pred: np.ndarray, true: np.ndarray, B: int = BOOT_B,
                       seed: int = BOOT_SEED) -> tuple[float, float, float]:
    """Pooled Pearson with row-bootstrap CI over the leading axis (SCMs)."""
    from scipy.stats import pearsonr
    n_scms = pred.shape[0]
    pt = pearsonr(pred.flatten(), true.flatten())[0]
    rng = np.random.default_rng(seed)
    boots = np.empty(B)
    for b in range(B):
        idx = rng.integers(0, n_scms, n_scms)
        boots[b] = pearsonr(pred[idx].flatten(), true[idx].flatten())[0]
    return pt, float(np.percentile(boots, 2.5)), float(np.percentile(boots, 97.5))


def _bootstrap_paired_delta(p1: np.ndarray, p2: np.ndarray, true: np.ndarray,
                            B: int = BOOT_B, seed: int = BOOT_SEED
                            ) -> tuple[float, float, float]:
    """Paired-bootstrap CI on Pearson(p1, true) - Pearson(p2, true)."""
    from scipy.stats import pearsonr
    n_scms = true.shape[0]
    d_pt = pearsonr(p1.flatten(), true.flatten())[0] - pearsonr(p2.flatten(), true.flatten())[0]
    rng = np.random.default_rng(seed)
    boots = np.empty(B)
    for b in range(B):
        idx = rng.integers(0, n_scms, n_scms)
        a = pearsonr(p1[idx].flatten(), true[idx].flatten())[0]
        c = pearsonr(p2[idx].flatten(), true[idx].flatten())[0]
        boots[b] = a - c
    return d_pt, float(np.percentile(boots, 2.5)), float(np.percentile(boots, 97.5))


def _f3(x: float) -> str:
    """Format a number to 3 decimals as $0.123$ for a tex cell. NaN → ---."""
    if not np.isfinite(x):
        return "---"
    return f"${x:.3f}$"


def _f3sub(point: float, lo: float, hi: float, *, sig: bool = False,
           bold: bool = False) -> str:
    r"""$0.921\;[0.88, 0.96]$, with optional bold and signed format."""
    if not np.isfinite(point):
        return "---"
    fmt = "+" if sig else ""
    s = f"${point:{fmt}.3f}\\;[{lo:{fmt}.2f},{hi:{fmt}.2f}]$"
    return f"$\\mathbf{{{s[1:-1]}}}$" if bold else s


# ---------------------------------------------------------------------------
# Table: held-out random DAGs (tab:held-out-dags)
# ---------------------------------------------------------------------------

HELD_OUT_DAGS_MAIN_ROWS: list[tuple[str, str]] = [
    ("FADO: $p{=}5$ ($100$k)",                 "eval_main_p5_50k"),
    ("$p{=}8$, 15k",                           "eval_p8_15k"),
    ("$p{=}13$, 20k",                          "eval_p13_20k"),
    ("$p{=}20$, 30k",                          "eval_p20_30k"),
    ("Gaussian control $p{=}5$",               "eval_gauss_control_p5"),
    ("Polynomial nonlinear $p{=}5$",           "eval_nonlinear_p5_20k_v2"),
    ("Random-MLP nonlinear $p{=}5$",           "eval_mlp_p5_20k"),
    ("Hidden confounder $p{=}5$",              "eval_hidden_p5_20k"),
    ("Mixed binary/continuous $p{=}5$",        "eval_mixed_p5_20k"),
]

HELD_OUT_DAGS_EXTENDED_ROWS: list[tuple[str, str]] = [
    ("Linear $p{=}5$, 15k steps",              "eval_main_p5_15k"),
    ("Large $p{=}5$ ($d{=}192$, 4+4)",         "eval_large_p5_30k"),
    ("Large $p{=}13$ ($d{=}192$, 4+4)",        "eval_large_p13_30k"),
    ("Gaussian control $p{=}8$",               "eval_gauss_p8_15k"),
    ("MLP + hidden confounder $p{=}5$",        "eval_mlp_hidden_p5_25k"),
    ("Hidden confounder $p{=}13$",             "eval_hidden_p13_25k"),
    ("Mixed $p{=}13$",                         "eval_mixed_p13_25k"),
]


def _held_out_dags_body(rows_spec: list[tuple[str, str]]) -> str:
    rows = []
    for label, tag in rows_spec:
        d = _load(RESULTS / f"{tag}.json")["random"]
        cells = [
            label,
            f"${d['pearson']['model']:.2f}$",
            f"${d['auroc_nonzero']['model']:.2f}$",
            f"${d['mae_zero_features']['model']:.2f}$",
            f"${d['pearson']['marginal']:.2f}$",
        ]
        rows.append(" & ".join(cells) + " \\\\")
    return (
        "\\begin{tabular}{lrrrr}\n"
        "\\toprule\n"
        " & \\multicolumn{3}{c}{FADO $\\tauhat$ vs $\\tau$} & Marginal baseline \\\\\n"
        "\\cmidrule(lr){2-4} \\cmidrule(lr){5-5}\n"
        "Training setting & Pearson $r$ & AUROC (nonzero) & MAE (zero) & Pearson $r$ \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )


def build_held_out_dags() -> None:
    _write(
        "held_out_dags",
        _held_out_dags_body(HELD_OUT_DAGS_MAIN_ROWS),
        f"tab:held-out-dags — {len(HELD_OUT_DAGS_MAIN_ROWS)} rows × FADO metrics",
    )
    _write(
        "held_out_dags_extended",
        _held_out_dags_body(HELD_OUT_DAGS_EXTENDED_ROWS),
        f"tab:held-out-dags-extended — {len(HELD_OUT_DAGS_EXTENDED_ROWS)} rows × FADO metrics",
    )


# ---------------------------------------------------------------------------
# Table: seed robustness (tab:seed-robust)
# ---------------------------------------------------------------------------

def build_seed_robust() -> None:
    # Foundation probe (fix-100k mixture heavy) seeds 0/1/2 evaluated on
    # linear non-Gaussian heavy at p=5, n=500. Seed 0 reuses the canonical
    # eval_main_p5_50k.json (the headline eval for that ckpt).
    p5 = [_load(RESULTS / "eval_main_p5_50k.json")["random"]["pearson"]["model"]]
    p5 += [_load(RESULTS / f"eval_main_p5_100k_mixture_heavy_seed{i}.json")["random"]["pearson"]["model"]
           for i in (1, 2)]

    def _stats(vals: list[float]) -> tuple[float, float]:
        a = np.array(vals)
        return float(a.mean()), float(a.std(ddof=1)) if len(a) > 1 else 0.0

    m5, s5 = _stats(p5)

    def _row(label, vals, mean, std):
        cells = [label] + [(f"${v:.3f}$" if v is not None else "—") for v in vals]
        cells.append(f"${mean:.3f} \\pm {std:.3f}$")
        return " & ".join(cells) + " \\\\"

    body = (
        "\\begin{tabular}{lrrrr}\n"
        "\\toprule\n"
        "Scale & Seed 0 & Seed 1 & Seed 2 & mean $\\pm$ std \\\\\n"
        "\\midrule\n"
        + _row("$p{=}5$", p5, m5, s5) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("seed_robust", body, "tab:seed-robust")


# ---------------------------------------------------------------------------
# Table: heterogeneous-p (tab:heterogeneous-p)
# ---------------------------------------------------------------------------

def build_heterogeneous_p() -> None:
    rows = []
    for p, tag_het, tag_ded in [
        (5,  "eval_hetero_p3_15_linear_evalp5",  "eval_main_p5_15k"),
        (8,  "eval_hetero_p3_15_linear_evalp8",  "eval_p8_15k"),
        (13, "eval_hetero_p3_15_linear_evalp13", "eval_p13_20k"),
    ]:
        het = _load(RESULTS / f"{tag_het}.json")["random"]["pearson"]["model"]
        ded = _load(RESULTS / f"{tag_ded}.json")["random"]["pearson"]["model"]
        gap_pts = round(100 * (het - ded))
        rows.append(f"${p}$ & ${het:.3f}$ & ${ded:.3f}$ & ${gap_pts:+d}$~pts \\\\")

    body = (
        "\\begin{tabular}{rrrr}\n"
        "\\toprule\n"
        "Eval $p$ & Heterogeneous & Dedicated & Gap \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("heterogeneous_p", body, "tab:heterogeneous-p")


# ---------------------------------------------------------------------------
# Table: motif stress tests (tab:motifs)
# ---------------------------------------------------------------------------

# Motif → key feature index in the SCM, paper label, paper structure string.
MOTIF_SPEC: list[tuple[str, str, str, list[int]]] = [
    # tag, key feature, paper label, structure description
    ("A_direct_cause",      "$X_1$", "A: direct cause $X_1\\!\\to\\!Y$",                          [0]),
    ("B_proxy",             "$X_2$", "B: proxy $X_1\\!\\to\\!Y,\\,X_1\\!\\to\\!X_2$",            [1]),
    ("C_observed_confounder","$X_1$","C: confounded $Z\\!\\to\\!X_1,\\,Z\\!\\to\\!Y$",            [0]),
    ("D_mediator",          "$X_1/X_2$","D: mediator $X_1\\!\\to\\!X_2\\!\\to\\!Y$",              [0, 1]),
    ("E_target_descendant", "$X_1$", "E: target-descendant leak $Y\\!\\to\\!X_1$",                [0]),
    ("F_collider_leakage",  "$C$",   "F: collider $X_1\\!\\to\\!C\\!\\leftarrow\\!Y$",            [1]),
]


def _motif_bootstrap_ci(d_motif: dict, feat_idx: int) -> tuple[float, float, float]:
    """Need raw per-instance tauhats. eval_main_p5_50k.json doesn't store them
    directly, but tau_hat_std + n_repeats lets us reconstruct an approximate
    CI; for the paper we use the bootstrap path instead."""
    rows = d_motif["rows"]
    row = rows[feat_idx]
    mean = row["tau_hat_mean"]
    std = row.get("tau_hat_std", 0.0)
    n = d_motif["n_repeats"]
    se = std / math.sqrt(n) if n > 0 else 0.0
    z = 1.959964
    return mean, mean - z * se, mean + z * se


def build_motifs() -> None:
    d = _load(RESULTS / "eval_main_p5_50k.json")["motifs"]
    rows = []
    for tag, key, label, feats in MOTIF_SPEC:
        info = d[tag]
        if len(feats) == 1:
            i = feats[0]
            row = info["rows"][i]
            true = row["tau_true_mean"]
            mean, lo, hi = _motif_bootstrap_ci(info, i)
            assoc = row["assoc_mean"]
            multi = row["multivariate_mean"]
            true_zero = abs(true) < 1e-6
            model_cell = _f3sub(mean, lo, hi, bold=true_zero)
            cells = [label, key, f"${true:.2f}$" if not true_zero else "$0$",
                     model_cell, f"${assoc:.2f}$", f"${multi:.2f}$"]
        else:
            i0, i1 = feats
            r0, r1 = info["rows"][i0], info["rows"][i1]
            t0, t1 = r0["tau_true_mean"], r1["tau_true_mean"]
            m0, lo0, hi0 = _motif_bootstrap_ci(info, i0)
            m1, lo1, hi1 = _motif_bootstrap_ci(info, i1)
            cells = [label, key,
                     f"${t0:.2f}/{t1:.2f}$",
                     f"{_f3sub(m0, lo0, hi0)}/{_f3sub(m1, lo1, hi1)}",
                     f"${r0['assoc_mean']:.2f}/{r1['assoc_mean']:.2f}$",
                     f"${r0['multivariate_mean']:.2f}/{r1['multivariate_mean']:.2f}$"]
        rows.append(" & ".join(cells) + " \\\\")

    body = (
        "\\begin{tabular}{l l r r r r}\n"
        "\\toprule\n"
        "Motif (structure) & Key feature & Truth & Model $\\tauhat$ & Marginal & Lin. reg. \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("motifs", body, "tab:motifs — 6 motif stress tests, 50 instances each")


# ---------------------------------------------------------------------------
# Tables: causal-baselines + predictive-baselines (tab:causal-baselines, tab:predictive-baselines)
# ---------------------------------------------------------------------------

BASELINE_SETTINGS: list[tuple[str, str]] = [
    ("Linear non-Gaussian $p{=}5$",     "linear_p5_laplace"),
    ("Linear non-Gaussian $p{=}8$",     "linear_p8_laplace"),
    ("Linear non-Gaussian $p{=}13$",    "linear_p13_laplace"),
    ("Linear Gaussian $p{=}5$",         "linear_p5_gaussian"),
    ("Polynomial nonlinear $p{=}5$",    "nonlinear_p5_laplace"),
    ("Random-MLP nonlinear $p{=}5$",    "mlp_p5_laplace"),
    ("Hidden confounder $p{=}5$",       "hidden_p5_laplace"),
    ("Mixed binary/continuous $p{=}5$", "mixed_p5_laplace"),
]

PROBE_NPZ = {
    "linear_p5_laplace":   "probe_linear_p5",
    "linear_p8_laplace":   "probe_linear_p8",
    "linear_p13_laplace":  "probe_linear_p13",
    "linear_p5_gaussian":  "probe_gauss_p5",
    "nonlinear_p5_laplace": "probe_poly_p5",
    "mlp_p5_laplace":      "probe_mlp_p5",
    "hidden_p5_laplace":   "probe_hidden_p5",
    "mixed_p5_laplace":    "probe_mixed_p5",
}


def _probe_pearson_ci(suffix: str) -> tuple[float, float, float]:
    npz = np.load(BOOT / f"{PROBE_NPZ[suffix]}.npz", allow_pickle=True)
    return _bootstrap_pearson(npz["pred"], npz["true"])


def build_causal_baselines() -> None:
    methods = [("lingam", "LiNGAM"), ("notears", "NOTEARS"),
               ("pc", "PC"), ("ges", "GES"), ("fci", "FCI"),
               ("doubleml", "DML$^\\dagger$"),
               ("causal_forest", "CF$^\\dagger$")]
    rows = []
    for label, suf in BASELINE_SETTINGS:
        cells = [label]
        method_vals = []
        for m, _ in methods:
            d = _load(RESULTS / f"{m}_{suf}.json")
            method_vals.append(d["pearson"])
        probe_pt, probe_lo, probe_hi = _probe_pearson_ci(suf)
        all_vals = method_vals + [probe_pt]
        # bold the per-row max
        i_max = int(np.nanargmax([v if np.isfinite(v) else -np.inf for v in all_vals]))
        for j, v in enumerate(method_vals):
            s = f"{v:.3f}"
            cells.append(f"$\\mathbf{{{s}}}$" if i_max == j else f"${s}$")
        probe_cell = _f3sub(probe_pt, probe_lo, probe_hi,
                            bold=(i_max == len(method_vals)))
        cells.append(probe_cell)
        rows.append(" & ".join(cells) + " \\\\")

    header = "Setting & " + " & ".join(lbl for _, lbl in methods) + " & FADO \\\\"
    col_spec = "l " + "r " * (len(methods) + 1)
    body = (
        "\\begin{tabular}{" + col_spec.strip() + "}\n"
        "\\toprule\n"
        + header + "\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("causal_baselines", body, "tab:causal-baselines")

    # Paired-bootstrap Δ for the Hidden confounder p=5 row (probe vs LiNGAM).
    # Cited inline in the tab:causal-baselines caption; emit as a separate
    # \input fragment so the caption stays in lockstep with the NPZs.
    probe = np.load(BOOT / "probe_hidden_p5.npz", allow_pickle=True)
    lingam = np.load(BOOT / "lingam_hidden_p5.npz", allow_pickle=True)
    if not np.allclose(probe["true"], lingam["true"]):
        raise RuntimeError("hidden_p5 probe/lingam NPZs are not SCM-aligned")
    d_pt, d_lo, d_hi = _bootstrap_paired_delta(
        probe["pred"], lingam["pred"], probe["true"]
    )
    delta_body = (
        "\\providecommand{\\HiddenConfounderPairedDelta}{"
        f"$\\Delta={d_pt:+.3f}$, $95\\%$ CI $[{d_lo:+.3f},{d_hi:+.3f}]$"
        "}\n"
    )
    _write("causal_baselines_hidden_delta", delta_body,
           "FADO - LiNGAM paired Δ on Hidden confounder p=5 row")


def build_offlabel_pfn() -> None:
    """Off-label per-feature application of interventional PFNs.

    Reads the CausalPFN per-setting JSONs that backed the original C-PFN
    row of tab:causal-baselines (now removed). The Do-PFN cell renders ---
    until the follow-up branch produces causal_probe/results/dopfn_<suf>.json
    files matching BASELINE_SETTINGS.
    """
    rows = []
    for label, suf in BASELINE_SETTINGS:
        cpfn = _load(RESULTS / f"causalpfn_{suf}.json")["pearson"]
        dopfn_path = RESULTS / f"dopfn_{suf}.json"
        if dopfn_path.exists():
            dopfn_cell = f"${_load(dopfn_path)['pearson']:.3f}$"
        else:
            dopfn_cell = "---"
        probe_pt, probe_lo, probe_hi = _probe_pearson_ci(suf)
        cells = [label, f"${cpfn:.3f}$", dopfn_cell,
                 _f3sub(probe_pt, probe_lo, probe_hi)]
        rows.append(" & ".join(cells) + " \\\\")
    body = (
        "\\begin{tabular}{l r r r}\n"
        "\\toprule\n"
        "Setting & CausalPFN$^\\ddagger$ & Do-PFN$^\\ddagger$ & FADO \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("causal_offlabel_pfn", body, "tab:offlabel-pfn")


def build_predictive_baselines() -> None:
    methods = [("marginal", "Marginal"), ("ridge", "Lin. reg."),
               ("permutation", "Permutation"), ("shap", "SHAP")]
    rows = []
    for label, suf in BASELINE_SETTINGS:
        cells = [label]
        method_vals = []
        for m, _ in methods:
            method_vals.append(_load(RESULTS / f"{m}_{suf}.json")["pearson"])
        probe_pt, probe_lo, probe_hi = _probe_pearson_ci(suf)
        # probe always wins this table → always bold probe
        for v in method_vals:
            cells.append(f"${v:.3f}$")
        cells.append(_f3sub(probe_pt, probe_lo, probe_hi, bold=True))
        rows.append(" & ".join(cells) + " \\\\")

    header = "Setting & " + " & ".join(lbl for _, lbl in methods) + " & FADO \\\\"
    col_spec = "l " + "r " * (len(methods) + 1)
    body = (
        "\\begin{tabular}{" + col_spec.strip() + "}\n"
        "\\toprule\n"
        + header + "\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("predictive_baselines", body, "tab:predictive-baselines")


# ---------------------------------------------------------------------------
# Table: semi-synthetic real-X (tab:semisynth-realx)
# ---------------------------------------------------------------------------

SEMISYNTH_ROWS: list[tuple[str, str]] = [
    ("diabetes / linear",          "ss_main_heavy_diabetes_linear"),
    ("diabetes / mixed nonlin.",   "ss_main_heavy_diabetes_mixed_nonlinear"),
    ("california / linear",        "ss_main_heavy_california_housing_linear"),
    ("california / mixed nonlin.", "ss_main_heavy_california_housing_mixed_nonlinear"),
    ("abalone / interaction",      "ss_main_heavy_abalone_interaction"),
]


def _ss_bootstrap_ci(npz_path: Path, kind: str) -> dict:
    """Compute pooled-Pearson and FP CIs from per-SCM arrays in npz.

    npz fields: pred, true, marginal, multivariate, kinds (object array of
    strings: 'real'/'proxy'/'noise'/'leak' per (scm, feature)).
    """
    from scipy.stats import pearsonr
    z = np.load(npz_path, allow_pickle=True)
    out: dict = {}
    for label, model_key in [("probe", "pred"), ("marg", "marginal"), ("multi", "multivariate")]:
        if model_key not in z.files:
            out[f"{label}_pearson"] = (float("nan"), float("nan"), float("nan"))
            continue
        pred = z[model_key]
        true = z["true"]
        n_scms = pred.shape[0]
        rng = np.random.default_rng(BOOT_SEED)
        boots = np.empty(BOOT_B)
        for b in range(BOOT_B):
            idx = rng.integers(0, n_scms, n_scms)
            boots[b] = pearsonr(pred[idx].flatten(), true[idx].flatten())[0]
        pt = pearsonr(pred.flatten(), true.flatten())[0]
        out[f"{label}_pearson"] = (pt, float(np.percentile(boots, 2.5)),
                                   float(np.percentile(boots, 97.5)))
    # FP_proxy and FP_noise: per-SCM mean |tauhat| on the decoy columns,
    # then bootstrap over SCMs.
    kinds = np.array(z["kinds"])
    for kind_label, fp_key in [("proxy", "fp_proxy"), ("noise", "fp_noise")]:
        for src, model_key in [("probe", "pred"), ("marg", "marginal")]:
            arr = z[model_key]
            n_scms = arr.shape[0]
            vals_per_scm = np.array([
                np.abs(arr[i, kinds[i] == kind_label]).mean()
                if (kinds[i] == kind_label).any() else np.nan
                for i in range(n_scms)
            ])
            valid = vals_per_scm[~np.isnan(vals_per_scm)]
            n_v = len(valid)
            if n_v == 0:
                out.setdefault(fp_key, {})[src] = (float("nan"),) * 3
                continue
            pt = float(valid.mean())
            rng = np.random.default_rng(BOOT_SEED + 1)
            boots = np.empty(BOOT_B)
            for b in range(BOOT_B):
                idx = rng.integers(0, n_v, n_v)
                boots[b] = valid[idx].mean()
            out.setdefault(fp_key, {})[src] = (pt, float(np.percentile(boots, 2.5)),
                                               float(np.percentile(boots, 97.5)))
    return out


def build_semisynth() -> None:
    """Use point estimates from JSON; bootstrap CIs from npz when present."""
    rows = []
    for label, tag in SEMISYNTH_ROWS:
        d = _load(RESULTS / f"{tag}.json")
        # Try to compute CIs from npz if available; otherwise CIs from JSON.
        npz_path = BOOT / f"{tag}.npz"
        ci = _ss_bootstrap_ci(npz_path, tag) if npz_path.exists() else {}
        # Pearson cells
        def _pcell(method_key: str, src: str, bold: bool) -> str:
            if f"{src}_pearson" in ci and np.isfinite(ci[f"{src}_pearson"][0]):
                pt, lo, hi = ci[f"{src}_pearson"]
                return _f3sub(pt, lo, hi, bold=bold)
            v = d["pearson"][method_key]
            return f"$\\mathbf{{{v:.3f}}}$" if bold else f"${v:.3f}$"

        # Find best Pearson among (model, marginal, multivariate)
        peas = [d["pearson"]["model"], d["pearson"]["marginal"], d["pearson"]["multivariate"]]
        i_best_p = int(np.nanargmax([v if np.isfinite(v) else -np.inf for v in peas]))

        # FP cells (lower is better)
        def _fpcell(fp_key: str, src: str, json_dict_key: str, bold: bool) -> str:
            if fp_key in ci and src in ci[fp_key] and np.isfinite(ci[fp_key][src][0]):
                pt, lo, hi = ci[fp_key][src]
                return _f3sub(pt, lo, hi, bold=bold)
            v = d[json_dict_key][src.replace("marg", "marginal").replace("probe", "model")]
            return f"$\\mathbf{{{v:.3f}}}$" if bold else f"${v:.3f}$"

        fp_proxy_pair = [d["fp_proxy"]["model"], d["fp_proxy"]["marginal"]]
        i_best_fpp = int(np.nanargmin(fp_proxy_pair))
        fp_noise_pair = [d["fp_noise"]["model"], d["fp_noise"]["marginal"]]
        i_best_fpn = int(np.nanargmin(fp_noise_pair))

        cells = [
            label,
            _pcell("model", "probe", bold=(i_best_p == 0)),
            _pcell("marginal", "marg", bold=(i_best_p == 1)),
            _pcell("multivariate", "multi", bold=(i_best_p == 2)),
            _fpcell("fp_proxy", "probe", "fp_proxy", bold=(i_best_fpp == 0)),
            _fpcell("fp_proxy", "marg",  "fp_proxy", bold=(i_best_fpp == 1)),
            _fpcell("fp_noise", "probe", "fp_noise", bold=(i_best_fpn == 0)),
            _fpcell("fp_noise", "marg",  "fp_noise", bold=(i_best_fpn == 1)),
        ]
        rows.append(" & ".join(cells) + " \\\\")

    header_top = (" & \\multicolumn{3}{c}{Pearson $(\\tauhat,\\tau)$}"
                  " & \\multicolumn{2}{c}{FP proxy $|\\tauhat|$}"
                  " & \\multicolumn{2}{c}{FP noise $|\\tauhat|$} \\\\")
    cmid = "\\cmidrule(lr){2-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}"
    header_bot = "Config & FADO & Marg. & Multi. & FADO & Marg. & FADO & Marg. \\\\"
    body = (
        "\\begin{tabular}{l r r r r r r r}\n"
        "\\toprule\n"
        + header_top + "\n"
        + cmid + "\n"
        + header_bot + "\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("semisynth_realx", body, "tab:semisynth-realx")


# ---------------------------------------------------------------------------
# Table: Hillstrom (tab:hillstrom)
# ---------------------------------------------------------------------------

HILLSTROM_ROWS: list[tuple[str, str, bool]] = [
    # label, bootstrap json tag, bold-row flag (the chosen headline)
    ("\\textbf{Mixture heavy (foundation)}", "hillstrom_main_heavy",            True),
    ("Mixture heavy / conversion",           "hillstrom_main_heavy_conversion", False),
]


def _bsub(point: float, ci: list[float], sig: bool = True, bold: bool = False) -> str:
    return _f3sub(point, ci[0], ci[1], sig=sig, bold=bold)


def build_hillstrom() -> None:
    rows = []
    for label, tag, bold in HILLSTROM_ROWS:
        d = _load(BOOT / f"{tag}.json")
        rct = d["tau_T_rct_mean"]
        cells = [
            label,
            f"${rct:+.2f}$" if "conversion" not in tag else f"${rct:+.3f}$",
            _bsub(d["tau_hat_T_mean"], d["tau_hat_T_ci"], bold=bold),
            _bsub(d["ATE_error_mean"], d["ATE_error_ci"], sig=False, bold=bold),
            _bsub(d["tau_hat_P_T_mean"], d["tau_hat_P_T_ci"]),
            _bsub(d["tau_hat_L_Y_mean"], d["tau_hat_L_Y_ci"]),
            _f3sub(d["null_MAE_mean"], d["null_MAE_ci"][0], d["null_MAE_ci"][1],
                   sig=False, bold=(not bold and tag in {"hillstrom_linear_p13", "hillstrom_mixed_p5", "hillstrom_mixed_p13_conversion"})),
        ]
        rows.append(" & ".join(cells) + " \\\\")

    body = (
        "\\begin{tabular}{l r r r r r r}\n"
        "\\toprule\n"
        "Ckpt & $\\tau_T^{\\mathrm{RCT}}$ & $\\tauhat_T$ & err & $\\tauhat_{P_T}$"
        " & $\\tauhat_{L_Y}$ (assoc 1.52) & null MAE \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("hillstrom", body, "tab:hillstrom")


# ---------------------------------------------------------------------------
# Table: SHAP contrast on Hillstrom (tab:shap-contrast)
# ---------------------------------------------------------------------------

SHAP_CONTRAST_ROWS = [
    # paper feature label, json key in DR/probe per_feature, SHAP rank, |SHAP|, truth
    ("Leak $L_Y$",          "L_Y (leak)",  "\\textbf{\\#1}", "3.67", "$0$"),
    ("Proxy $P_T$",         "P_T (proxy)", "\\#7",          "0.07", "$0$"),
    ("noise$_1$",           "noise_1",     "---",           "0.07", "$0$"),
    ("noise$_2$",           "noise_2",     "---",           "0.09", "$0$"),
    ("noise$_3$",           "noise_3",     "---",           "0.07", "$0$"),
    ("$T_{\\mathrm{true}}$", "T_true",     "\\#3",          "0.09", "$+0.22$ RCT"),
    ("newbie",              "newbie",      "\\#2",          "0.13", "real"),
    ("history",             "history",     "\\#5",          "0.08", "real"),
    ("recency",             "recency",     "\\#9",          "0.05", "real"),
    ("mens",                "mens",        "---",           "---",  "real"),
    ("womens",              "womens",      "---",           "---",  "real"),
]


def build_shap_contrast() -> None:
    dr = _load(BOOT / "drlearner_hillstrom_visit.json")["per_feature"]
    probe = _load(BOOT / "hillstrom_main_heavy.json")["per_feature"]
    rows = []
    for paper_label, key, rank, shap, truth in SHAP_CONTRAST_ROWS:
        dr_e = dr[key]
        pr_e = probe[key]
        dr_cell = _f3sub(dr_e["mean"], dr_e["ci"][0], dr_e["ci"][1], sig=True,
                         bold=(key == "L_Y (leak)"))
        pr_cell = _f3sub(pr_e["mean"], pr_e["ci"][0], pr_e["ci"][1], sig=True,
                         bold=(key == "L_Y (leak)"))
        rows.append(" & ".join([paper_label, rank, f"${shap}$" if shap != "---" else "---",
                                dr_cell, pr_cell, truth]) + " \\\\")

    body = (
        "\\begin{tabular}{l r r r r r}\n"
        "\\toprule\n"
        "Feature & SHAP rank & $|\\mathrm{SHAP}|$ & DR-Learner $\\tauhat$ & FADO $\\tauhat$ & Truth \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("shap_contrast", body, "tab:shap-contrast")


# ---------------------------------------------------------------------------
# Table: Tübingen (tab:tubingen)
# ---------------------------------------------------------------------------

TUBINGEN_ROWS = [
    ("Hetero linear",                  "tubingen_hetero_linear"),
    ("$p{=}13$",                       "tubingen_p13"),
    ("MLP $p{=}5$",                    "tubingen_mlp_p5"),
    ("Mixture heavy (foundation)",     "tubingen_main_p5_50k_mixture_heavy"),
]


def build_tubingen() -> None:
    rows = []
    for label, tag in TUBINGEN_ROWS:
        d = _load(RESULTS / f"{tag}.json")
        n = d["n_pairs_evaluated"]
        acc = d["direction_accuracy"]
        wacc = d["weighted_accuracy"]
        k = round(acc * n)
        lo, hi = _wilson(acc, n)
        rows.append(f"{label} & ${acc:.2f}_{{[{lo:.2f},{hi:.2f}]}}$ & ${wacc:.2f}$ \\\\")

    body = (
        "\\begin{tabular}{l r r}\n"
        "\\toprule\n"
        "Model variant & Accuracy & Weighted accuracy \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("tubingen", body, "tab:tubingen")


# ---------------------------------------------------------------------------
# Table: Sachs (tab:sachs-ckpts)
# ---------------------------------------------------------------------------

SACHS_ROWS = [
    ("Linear $p{=}5$, 15k",          "sachs_p5"),
    ("$p{=}8$, 15k",                 "sachs_p8"),
    ("$p{=}13$, 20k",                "sachs_p13"),
    ("Mixture heavy (foundation)",   "sachs_main_heavy"),
]


def build_sachs() -> None:
    from scipy.stats import pearsonr
    rows = []
    for label, tag in SACHS_ROWS:
        z = np.load(BOOT / f"{tag}.npz", allow_pickle=True)
        pred = z["pred"]; true = z["true"]
        marg = z["marginal"]; multi = z["multivariate"]
        n = pred.shape[0]
        ppt = pearsonr(pred.flatten(), true.flatten())[0]
        pmt = pearsonr(marg.flatten(), true.flatten())[0]
        pvt = pearsonr(multi.flatten(), true.flatten())[0]
        rng = np.random.default_rng(BOOT_SEED)
        bp, bm, bv, bd = (np.empty(BOOT_B) for _ in range(4))
        for b in range(BOOT_B):
            idx = rng.integers(0, n, n)
            bp[b] = pearsonr(pred[idx].flatten(), true[idx].flatten())[0]
            bm[b] = pearsonr(marg[idx].flatten(), true[idx].flatten())[0]
            bv[b] = pearsonr(multi[idx].flatten(), true[idx].flatten())[0]
            bd[b] = bp[b] - bm[b]
        cells = [
            label,
            _f3sub(ppt, np.percentile(bp, 2.5), np.percentile(bp, 97.5)),
            _f3sub(ppt - pmt, np.percentile(bd, 2.5), np.percentile(bd, 97.5), sig=True),
            _f3sub(pmt, np.percentile(bm, 2.5), np.percentile(bm, 97.5)),
            _f3sub(pvt, np.percentile(bv, 2.5), np.percentile(bv, 97.5)),
        ]
        rows.append(" & ".join(cells) + " \\\\")

    body = (
        "\\begin{tabular}{l r r r r}\n"
        "\\toprule\n"
        "Variant        & FADO & $\\Delta$ vs Marg.\\ & Marginal & Multivariate \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("sachs_ckpts", body, "tab:sachs-ckpts")


# ---------------------------------------------------------------------------
# Table: LaLonde (tab:lalonde)
# ---------------------------------------------------------------------------

LALONDE_ROWS: list[tuple[str, str, bool]] = [
    ("\\textbf{Mixture heavy (foundation) / CPS3}", "lalonde_main_heavy", True),
]


def build_lalonde() -> None:
    rows = []
    for label, tag, bold in LALONDE_ROWS:
        d = _load(BOOT / f"{tag}.json")
        rct = d["tau_T_rct"]
        cells = [
            label,
            f"${rct:+.3f}$",
            _bsub(d["tau_hat_T_mean"], d["tau_hat_T_ci"], bold=bold),
            _bsub(d["ATE_error_mean"], d["ATE_error_ci"], sig=False, bold=bold),
            _bsub(d["tau_hat_L_Y_mean"], d["tau_hat_L_Y_ci"]),
        ]
        rows.append(" & ".join(cells) + " \\\\")

    body = (
        "\\begin{tabular}{l r r r r}\n"
        "\\toprule\n"
        "Config & $\\tau_{\\mathrm{RCT}}$ & $\\tauhat_T$ & err & $\\tauhat_{L_Y}$ (assoc 1.92) \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("lalonde", body, "tab:lalonde")


# ---------------------------------------------------------------------------
# Table: Criteo (tab:criteo)
# ---------------------------------------------------------------------------

CRITEO_ROWS: list[tuple[str, str, bool]] = [
    ("\\textbf{Mixture heavy (foundation)}", "criteo_main_heavy", True),
]


def build_criteo() -> None:
    rows = []
    for label, tag, bold in CRITEO_ROWS:
        d = _load(BOOT / f"{tag}.json")
        cells = [
            label,
            f"${d['tau_T_rct']:+.3f}$",
            _bsub(d["tau_hat_T_mean"], d["tau_hat_T_ci"], bold=bold),
            _bsub(d["tau_hat_L_Y_mean"], d["tau_hat_L_Y_ci"]),
            _bsub(d["null_MAE_mean"], d["null_MAE_ci"], sig=False, bold=bold),
        ]
        rows.append(" & ".join(cells) + " \\\\")

    body = (
        "\\begin{tabular}{l r r r r}\n"
        "\\toprule\n"
        "Ckpt & $\\tau_{\\mathrm{RCT}}$ & $\\tauhat_T$ & $\\tauhat_{L_Y}$ (assoc $\\sim 2$) & null MAE \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("criteo", body, "tab:criteo")


# ---------------------------------------------------------------------------
# Table: ensemble uncertainty (tab:ensemble)
# ---------------------------------------------------------------------------

ENSEMBLE_ROWS = [
    ("Linear, Laplace",            "ensemble_linear_p5_laplace"),
    ("Linear, Gaussian",           "ensemble_linear_p5_gauss"),
    ("Hidden confounder, Laplace", "ensemble_hidden_p5"),
    ("Random-MLP, Laplace",        "ensemble_mlp_p5"),
    ("Mixed type, Laplace",        "ensemble_mixed_p5"),
]


def build_ensemble() -> None:
    rows = []
    for label, tag in ENSEMBLE_ROWS:
        d = _load(RESULTS / f"{tag}.json")
        n = d["n_scms"]
        p = d["p"]
        pe = d["pearson_std_err"]
        sp = d["spearman_std_err"]
        cv = d["coverage_2sigma"]
        pe_lo, pe_hi = _fz_ci(pe, n)
        sp_lo, sp_hi = _fz_ci(sp, n)
        cv_lo, cv_hi = _wilson(cv, n * p)
        cells = [
            label,
            f"${pe:+.3f}_{{[{pe_lo:+.2f},{pe_hi:+.2f}]}}$",
            f"${sp:+.3f}_{{[{sp_lo:+.2f},{sp_hi:+.2f}]}}$",
            f"${cv:.3f}_{{[{cv_lo:.2f},{cv_hi:.2f}]}}$",
        ]
        rows.append(" & ".join(cells) + " \\\\")

    body = (
        "\\begin{tabular}{l r r r}\n"
        "\\toprule\n"
        "Regime & Pearson$(\\sigma,|\\mathrm{err}|)$ & Spearman & Coverage $\\mu\\pm 2\\sigma$ \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("ensemble", body, "tab:ensemble")


# ---------------------------------------------------------------------------
# Table: architecture ablations (tab:ablations)
# ---------------------------------------------------------------------------

ABLATION_ROWS: list[tuple[str, str | None, bool]] = [
    ("Linear $p{=}5$ (all components)",  "eval_main_p5_50k",                  True),
    ("$-$ row attention",                "eval_ablation_no_row_attn_p5_50000", False),
    ("$-$ column attention",             "eval_ablation_no_col_attn_p5_50000", False),
    ("$-$ type embedding (feature/$Y$)", "eval_ablation_no_type_emb_p5_50000", False),
]


def build_ablations() -> None:
    main = _load(RESULTS / "eval_main_p5_50k.json")["random"]
    main_pearson = main["pearson"]["model"]
    rows = []
    for label, tag, is_main in ABLATION_ROWS:
        d = _load(RESULTS / f"{tag}.json")["random"]
        pe = d["pearson"]["model"]
        n = d["n_scms"]
        lo, hi = _fz_ci(pe, n)
        if is_main:
            cells = [label, _f3sub(pe, lo, hi, bold=True), "—", "—", "—"]
        else:
            r2 = d["r2"]["model"]
            au = d["auroc_nonzero"]["model"]
            change_pct = round(100 * (pe - main_pearson) / main_pearson)
            cells = [label, _f3sub(pe, lo, hi),
                     f"${r2:.3f}$", f"${au:.3f}$",
                     f"${change_pct:+d}\\%$"]
        rows.append(" & ".join(cells) + " \\\\")

    body = (
        "\\begin{tabular}{l r r r r}\n"
        "\\toprule\n"
        "Configuration & Pearson & $R^2$ & AUROC (nonzero) & Change in $R^2$ \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("ablations", body, "tab:ablations")


# ---------------------------------------------------------------------------
# Table: type-flip ablation (tab:type-flip-ablation)
# ---------------------------------------------------------------------------

def build_type_flip() -> None:
    d = _load(RESULTS / "ablation_type_flip_main_p5_50k.json")["results"]
    label_for = {"normal": "Normal (col $p$ marked)",
                 "all_zero": "All zero (no column marked)",
                 "mispointed": "Mispointed (col $0$ marked)"}
    order = ["normal", "all_zero", "mispointed"]
    rows = []
    for k in order:
        e = d[k]
        cells = [label_for[k],
                 f"${e['pearson_truth']:.3f}$",
                 f"${e['mae_zero_features']:.3f}$",
                 f"${e['pearson_vs_normal']:.3f}$"]
        rows.append(" & ".join(cells) + " \\\\")

    body = (
        "\\begin{tabular}{l r r r}\n"
        "\\toprule\n"
        "Type-id config & Pearson($\\hat\\tau,\\tau$) & MAE (zero) & Pearson($\\hat\\tau,\\hat\\tau_{\\mathrm{normal}}$) \\\\\n"
        "\\midrule\n"
        + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    _write("type_flip", body, "tab:type-flip-ablation")


# ---------------------------------------------------------------------------

ALL_BUILDERS = [
    build_held_out_dags,
    build_seed_robust,
    build_heterogeneous_p,
    build_motifs,
    build_causal_baselines,
    build_offlabel_pfn,
    build_predictive_baselines,
    build_semisynth,
    build_hillstrom,
    build_shap_contrast,
    build_tubingen,
    build_sachs,
    build_lalonde,
    build_criteo,
    build_ensemble,
    build_ablations,
    build_type_flip,
]


def main() -> None:
    TABLES.mkdir(parents=True, exist_ok=True)
    for fn in ALL_BUILDERS:
        print(f"--- {fn.__name__}")
        try:
            fn()
        except Exception as e:
            print(f"  FAIL: {type(e).__name__}: {e}")


if __name__ == "__main__":
    main()
