"""Reduce the per-chunk identifiable-SCM SHAP-vs-causal analysis into
the aggregate numbers we'll cite in the paper."""
from __future__ import annotations

import argparse
import glob
import os
import pickle
from collections import defaultdict

import numpy as np


CELLS = (
    ("ridge_int",  "Ridge / int.",         r"\shortstack{Ridge \\ interventional}"),
    ("ridge_cond", "Ridge / cond.",        r"\shortstack{Ridge \\ conditional}"),
    ("lgbm_path",  "LightGBM / path-dep.", r"\shortstack{LightGBM \\ path-dependent}"),
    ("lgbm_int",   "LightGBM / int.",      r"\shortstack{LightGBM \\ interventional}"),
)


def _safe_mean(values):
    arr = np.asarray([v for v in values if v is not None and np.isfinite(v)])
    return float(arr.mean()) if arr.size else float("nan")


def _pct_with_cm(rs, cell):
    flags = [r.get(f"has_causal_misleading_{cell}") for r in rs]
    flags = [bool(f) for f in flags if f is not None]
    if not flags:
        return float("nan")
    return 100.0 * np.mean(flags)


def _pct_features_cm(rs, cell):
    fracs = [r.get(f"frac_causal_misleading_{cell}") for r in rs]
    return 100.0 * _safe_mean(fracs)


def _rho_shap_truetau(rs, cell):
    return _safe_mean([r.get(f"shap_truetau_spearman_{cell}") for r in rs])


def _write_robustness_grid(by_family, out_tex):
    fams = [("lingam", "LiNGAM"), ("anm", "ANM"), ("tree", "Tree"), ("all", "All")]
    cells_present = [(k, _disp, _tex) for (k, _disp, _tex) in CELLS
                     if any(r.get(f"has_causal_misleading_{k}") is not None
                            for r in by_family.get("all", []))]
    if not cells_present:
        print(f"[warn] no per-cell fields found in chunks; skipping {out_tex}")
        return
    with open(out_tex, "w") as f:
        f.write("% Auto-generated by shap_failure_identifiable_reduce.py\n")
        f.write("% rows: SCM family; cols: SHAP variant; cell: %% of DGPs with at least one causal-misleading feature.\n")
        f.write("\\begin{tabular}{l" + "r" * len(cells_present) + "}\n")
        f.write("\\toprule\n")
        f.write("Family & " + " & ".join(tex for (_, _, tex) in cells_present) + " \\\\\n")
        f.write("\\midrule\n")
        for fam_key, fam_label in fams:
            rs = by_family.get(fam_key, [])
            cells = [fam_label]
            for cell, _, _ in cells_present:
                v = _pct_with_cm(rs, cell)
                cells.append(f"${v:.1f}$" if np.isfinite(v) else "---")
            f.write(" & ".join(cells) + " \\\\\n")
        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")
    print(f"Robustness grid written to {out_tex}")


def _write_robustness_full(by_family, out_tex):
    fams = [("lingam", "LiNGAM"), ("anm", "ANM"), ("tree", "Tree"), ("all", "All")]
    cells_present = [(k, _disp, _tex) for (k, _disp, _tex) in CELLS
                     if any(r.get(f"has_causal_misleading_{k}") is not None
                            for r in by_family.get("all", []))]
    if not cells_present:
        return
    rows = [
        (r"\% DGPs causal-misleading", _pct_with_cm, True),
        (r"\% features causal-misleading", _pct_features_cm, True),
        (r"$\rho(|\mathrm{SHAP}|, |\tau|)$", _rho_shap_truetau, False),
    ]
    with open(out_tex, "w") as f:
        f.write("% Auto-generated by shap_failure_identifiable_reduce.py\n")
        f.write("\\begin{tabular}{ll" + "r" * len(cells_present) + "}\n")
        f.write("\\toprule\n")
        f.write("Metric & Family & " + " & ".join(tex for (_, _, tex) in cells_present) + " \\\\\n")
        f.write("\\midrule\n")
        for r_idx, (metric_label, fn, is_pct) in enumerate(rows):
            for f_idx, (fam_key, fam_label) in enumerate(fams):
                rs = by_family.get(fam_key, [])
                cells = [metric_label if f_idx == 0 else "", fam_label]
                for cell, _, _ in cells_present:
                    v = fn(rs, cell)
                    if not np.isfinite(v):
                        cells.append("---")
                    elif is_pct:
                        cells.append(f"${v:.1f}$")
                    else:
                        cells.append(f"${v:+.3f}$")
                f.write(" & ".join(cells) + " \\\\\n")
            if r_idx < len(rows) - 1:
                f.write("\\midrule\n")
        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")
    print(f"Robustness appendix table written to {out_tex}")


def _paired_pearson_cm(by_family, cell_a, cell_b):
    rs = by_family.get("all", [])
    a = [int(bool(r.get(f"has_causal_misleading_{cell_a}"))) for r in rs
         if r.get(f"has_causal_misleading_{cell_a}") is not None
         and r.get(f"has_causal_misleading_{cell_b}") is not None]
    b = [int(bool(r.get(f"has_causal_misleading_{cell_b}"))) for r in rs
         if r.get(f"has_causal_misleading_{cell_a}") is not None
         and r.get(f"has_causal_misleading_{cell_b}") is not None]
    if len(a) < 2 or float(np.std(a)) == 0 or float(np.std(b)) == 0:
        return float("nan")
    return float(np.corrcoef(a, b)[0, 1])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--chunks-dir", default="results/chunks_ident")
    ap.add_argument("--out-tex", default=None,
                    help="Optional path to write a LaTeX table fragment.")
    ap.add_argument("--out-tex-robustness", default=None,
                    help="Optional path to write the SHAP-variants robustness grid.")
    ap.add_argument("--out-tex-robustness-full", default=None,
                    help="Optional path to write the SHAP-variants robustness appendix table.")
    args = ap.parse_args()

    paths = sorted(glob.glob(os.path.join(args.chunks_dir, "chunk_*.pkl")))
    print(f"Reducing {len(paths)} chunk files from {args.chunks_dir}")

    by_family = defaultdict(list)
    for p in paths:
        with open(p, "rb") as f:
            d = pickle.load(f)
        for r in d["results"]:
            by_family[r["family"]].append(r)
    by_family["all"] = [r for rows in list(by_family.values()) for r in rows]

    fields = [
        ("n DGPs", "$n$ DGPs",
         lambda rs: len(rs)),
        ("% with causal-misleading", r"\% with causal-misleading",
         lambda rs: 100 * np.mean([r["has_causal_misleading"] for r in rs])),
        ("% features causal-misleading", r"\% features causal-misleading",
         lambda rs: 100 * np.mean([r["frac_causal_misleading"] for r in rs])),
        ("Sp(SHAP, |true tau|)", r"$\rho(|\mathrm{SHAP}|, |\tau|)$",
         lambda rs: _safe_mean([r["shap_truetau_spearman"] for r in rs])),
        ("Sp(probe_lin, |true tau|)", r"$\rho(|\hat\tau_{\mathrm{lin}}|, |\tau|)$",
         lambda rs: _safe_mean([r.get("probe_linear_p5_50k_truetau_spearman") for r in rs])),
        ("Sp(probe_mlp, |true tau|)", r"$\rho(|\hat\tau_{\mathrm{mlp}}|, |\tau|)$",
         lambda rs: _safe_mean([r.get("probe_mlp_p5_20k_truetau_spearman") for r in rs])),
        ("Pearson(probe_lin, true tau)", r"$r(\hat\tau_{\mathrm{lin}}, \tau)$",
         lambda rs: _safe_mean([r.get("probe_linear_p5_50k_truetau_pearson") for r in rs])),
        ("Pearson(probe_mlp, true tau)", r"$r(\hat\tau_{\mathrm{mlp}}, \tau)$",
         lambda rs: _safe_mean([r.get("probe_mlp_p5_20k_truetau_pearson") for r in rs])),
        ("% probe_lin correct on misleading", r"\% FADO$_{\mathrm{lin}}$ zeros misleading",
         lambda rs: _safe_mean([r.get("probe_linear_p5_50k_correct_on_causal_misleading") for r in rs]) * 100),
        ("% probe_mlp correct on misleading", r"\% FADO$_{\mathrm{mlp}}$ zeros misleading",
         lambda rs: _safe_mean([r.get("probe_mlp_p5_20k_correct_on_causal_misleading") for r in rs]) * 100),
    ]

    print()
    print(f"{'metric':<40} | " + " | ".join(f"{fam:>9}" for fam in ["lingam", "anm", "tree", "all"]))
    print("-" * 96)
    for label, _tex_label, fn in fields:
        is_pct = label.startswith("%")
        row = []
        for fam in ["lingam", "anm", "tree", "all"]:
            rs = by_family.get(fam, [])
            try:
                v = fn(rs)
                if isinstance(v, float):
                    if is_pct:
                        row.append(f"{v:>9.1f}")
                    else:
                        row.append(f"{v:>+9.3f}" if abs(v) < 10 else f"{v:>9.1f}")
                else:
                    row.append(f"{v:>9}")
            except Exception:
                row.append("       NA")
        print(f"{label:<40} | " + " | ".join(row))

    if args.out_tex:
        with open(args.out_tex, "w") as f:
            f.write("% Auto-generated by shap_failure_identifiable_reduce.py\n")
            f.write("\\begin{tabular}{lrrrr}\n")
            f.write("\\toprule\n")
            f.write("Metric & LiNGAM & ANM & Tree & All \\\\\n")
            f.write("\\midrule\n")
            for _label, tex_label, fn in fields:
                is_pct = _label.startswith("%")
                cells = [tex_label]
                for fam in ["lingam", "anm", "tree", "all"]:
                    rs = by_family.get(fam, [])
                    try:
                        v = fn(rs)
                        if isinstance(v, float):
                            if is_pct:
                                cells.append(f"${v:.1f}$")
                            elif abs(v) < 10:
                                cells.append(f"${v:+.3f}$")
                            else:
                                cells.append(f"${v:.1f}$")
                        else:
                            cells.append(f"${v}$")
                    except Exception:
                        cells.append("---")
                f.write(" & ".join(cells) + " \\\\\n")
            f.write("\\bottomrule\n")
            f.write("\\end{tabular}\n")
        print(f"\nLaTeX fragment written to {args.out_tex}")

    if args.out_tex_robustness:
        _write_robustness_grid(by_family, args.out_tex_robustness)
    if args.out_tex_robustness_full:
        _write_robustness_full(by_family, args.out_tex_robustness_full)

    print()
    print("SHAP-variants robustness grid (% of DGPs with causal-misleading)")
    print(f"{'family':<8} | " + " | ".join(f"{disp:>22}" for (_, disp, _) in CELLS))
    print("-" * 100)
    for fam_key in ["lingam", "anm", "tree", "all"]:
        rs = by_family.get(fam_key, [])
        row = []
        for cell, _, _ in CELLS:
            v = _pct_with_cm(rs, cell)
            row.append(f"{v:>22.1f}" if np.isfinite(v) else f"{'NA':>22}")
        print(f"{fam_key:<8} | " + " | ".join(row))

    print()
    print("Per-DGP causal-misleading flag — Pearson correlation across cells (paired):")
    cell_keys = [c[0] for c in CELLS]
    for i, ca in enumerate(cell_keys):
        for cb in cell_keys[i + 1:]:
            r = _paired_pearson_cm(by_family, ca, cb)
            print(f"  {ca:<11} vs {cb:<11} : r = {r:+.3f}")


if __name__ == "__main__":
    main()
